[build]
command = "npm run build"
publish = "build"

[[plugins]]
package = "netlify-plugin-submit-sitemap"

[plugins.inputs]

# The base url of your site (optional, default = main URL set in Netlify)
baseUrl = "https://antoinegreuzard.fr"

# Path to the sitemap URL (optional, default = /sitemap.xml)
sitemapPath = "/sitemap.xml"

# Time in seconds to not submit the sitemap after successful submission
ignorePeriod = 0

# Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
providers = [
  "google",
]

[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
buildDir = "build"
prettyURLs = true
baseUrl = "https://antoinegreuzard.fr"


[[plugins]]
package = "@netlify/plugin-lighthouse"

[plugins.inputs.settings]
locale = "fr" # generates Lighthouse reports in fr

# to audit a specific absolute url
[[plugins.inputs.audits]]
url = "https://antoinegreuzard.fr/"

[[plugins]]
package = "netlify-plugin-image-optim"

[[headers]]
for = "/*"
[headers.values]
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://www.google-analytics.com; frame-src 'none'; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://www.google-analytics.com; object-src 'none'; media-src 'none'; form-action 'self'; upgrade-insecure-requests"
