[build]
command = "npm run build && npm run compress-brotli"
publish = "build"

# Configuration de cache optimisée
[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Configuration des en-têtes pour les fichiers Brotli
[[headers]]
for = "/*.html.br"
[headers.values]
Content-Encoding = "br"
Content-Type = "text/html; charset=utf-8"

[[headers]]
for = "/*.css.br"
[headers.values]
Content-Encoding = "br"
Content-Type = "text/css; charset=utf-8"

[[headers]]
for = "/*.js.br"
[headers.values]
Content-Encoding = "br"
Content-Type = "application/javascript; charset=utf-8"

[[plugins]]
package = "netlify-plugin-submit-sitemap"

[plugins.inputs]

# The base url of your site (optional, default = main URL set in Netlify)
baseUrl = "https://antoinegreuzard.fr"

# Path to the sitemap URL (optional, default = /sitemap.xml)
sitemapPath = "/sitemap.xml"

# Time in seconds to not submit the sitemap after successful submission
ignorePeriod = 0

# Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
providers = [
    "google",
]

[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
buildDir = "build"
prettyURLs = true
baseUrl = "https://antoinegreuzard.fr"


[[plugins]]
package = "@netlify/plugin-lighthouse"

[plugins.inputs.settings]
locale = "fr" # generates Lighthouse reports in fr

# to audit a specific absolute url
[[plugins.inputs.audits]]
url = "https://www.antoinegreuzard.fr/"

[[plugins]]
package = "netlify-plugin-image-optim"
