[build]
command = "npm run build"
publish = "build"

[[plugins]]
package = "netlify-plugin-submit-sitemap"

[plugins.inputs]

# The base url of your site (optional, default = main URL set in Netlify)
baseUrl = "https://antoinegreuzard.fr"

# Path to the sitemap URL (optional, default = /sitemap.xml)
sitemapPath = "/sitemap.xml"

# Time in seconds to not submit the sitemap after successful submission
ignorePeriod = 0

# Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
providers = [
    "google",
]

[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
buildDir = "build"
prettyURLs = true
baseUrl = "https://antoinegreuzard.fr"


[[plugins]]
package = "@netlify/plugin-lighthouse"

[plugins.inputs.settings]
locale = "fr" # generates Lighthouse reports in fr

# to audit a specific absolute url
[[plugins.inputs.audits]]
url = "https://antoinegreuzard.fr/"

[[plugins]]
package = "netlify-plugin-image-optim"
